### ISSUE TITLE
Have a way for key_map to not mess with visual selection

### ISSUE THREAD

**Issue by Chronial** [amoffat/snake#22]
I tried to implement a custom text object, but couldn't use `key_map` for the vmode part, as it always messes with the visual mode selection. It would be could if there was a keyword argument to disable the special vmode handling.

**Comment by amoffat** [comment]
I'm not sure I understand the problem.  You are using a `key_map` with `VISUAL_MODE` and what is it doing to your visual mode selection?  Can you attach some sample code?

**Comment by Chronial** [comment]
Here's a code example:
```python
import re, snake, vim
@snake.key_map('iu', mode='v')
def select_inside_underscore():
    line = vim.current.line
    _, col = vim.current.window.cursor

    start = re.search('[^\W_]*$', line[:col]).start()
    end = start + len(re.search('^[^\W_]*', line[start:]).group(0))
    if start != end:
        snake.keys('{}|v{}|'.format(start+1, end))
```

Put your cursor like this `some_und|erscore` and press `viu`. This is supposed to select `some_[underscore]`, which is not possible to implement with the current `key_map` – at least as far as I can see.

**Comment by amoffat** [comment]
I believe your `v` in `snake.keys` is exiting visual mode.  You're already in visual mode when you hit `viu` and your key mapped function executes.  Try just moving your cursor and you should be able to select whatever you want.

**Comment by Chronial** [comment]
No, the problem is the special handling as described in the ticket. I'm currently using a copy of snake's `key_map` with the visual mode wrapper removed and it works fine.

See also here: http://vim.wikia.com/wiki/Creating_new_text_objects

I'm also a little bit confused by this, but I think the `v` actually enters visual mode because the keys are send via `normal`.

**Comment by amoffat** [comment]
Text objects...learned something new about vim :)  Very powerful feature.  Sorry, I thought you were just referring to the text you were trying to select.

Does this not work for you?
```python
import re, snake, vim
@snake.key_map('iu', mode='v')
def select_inside_underscore(selected):
    line = vim.current.line
    _, col = vim.current.window.cursor

    start = re.search('[^\W_]*$', line[:col]).start()
    end = start + len(re.search('^[^\W_]*', line[start:]).group(0))
    if start != end:
        snake.keys('\<esc>{}|v{}|'.format(start+1, end))
```

The change here is that I'm escaping out of visual mode before moving and going into visual mode again.  Before, we were in visual mode, moving to some character, exiting visual mode, then moving to another character.

**Comment by Chronial** [comment]
I don't think trying to work around your visual-mode extension is a good idea. Imho there just should be a way to make `key_map` behave the expected way.

**Comment by amoffat** [comment]
I understand.  Let's walk through this so we both have the same expectation of what the expected behavior is:

1. go into visual mode
2. press `3|`
4. press `v`
5. press `10|`

Or, as a `.vimrc` keymapping: `vnoremap iu 3\|v10\|`

What is the result?  Nothing is selected, and your cursor is at column 10.  Can we both agree that although this is not desired behavior (the desired behavior being selecting from column 3 to 10), it is expected behavior?

I do believe you have stumbled upon a bug though (and I am actively looking into it), as evidenced by getting the desired behavior from the above input by disabling some snake code.  This bug, however, I believe is orthogonal to the key sequence required (in vim and snake) to get the desired behavior.

What do you think?

**Comment by Chronial** [comment]
That is not my expectation. `snake.keys` calls `:normal`, which is different from just pressing keys. Given that, I expect snake to behave the same way as vimscript.

And in vimscript, it's `vnoremap af :<C-U>silent! normal! [zV]z<CR>` (from http://vim.wikia.com/wiki/Creating_new_text_objects) or in this case `vnoremap iu :<C-U>normal 3|v10|<CR>`.

So since `keys` does `:normal`, I expect this to work:
```python
@snake.key_map('iu', mode='v')
def select_inside_underscore():
       snake.keys('3|v10|')
```

If you want this to behave like `vnoremap iu 3\|v10\|`, I think you will just have tons of problems, `normal` just doesn't do that. You might be looking for [`feedkeys`](http://vimdoc.sourceforge.net/htmldoc/eval.html#feedkeys()).

**Comment by amoffat** [comment]
Interesting.  There are some nuances I don't think I have a good grasp on yet.  For example, I'm actually really confused on the following:

`vnoremap iu :<C-U>echom mode(1)<CR>`

prints 'n', even though I imagine the mode *should* be 'v'.  also:

`vnoremap iu :<C-U>normal! v<CR>`

preserves visual mode, while:

`vnoremap iu :<C-U>normal! vv<CR>`

exits it.

So it does seem like `normal` can enter/exit visual mode from within a visual key map, but It seems like if a visual mode key map is engaged, the mode instantly becomes normal mode first.  Do you have any insight into this?

**Comment by Chronial** [comment]
Keymappings have nothing to do with that. They behave exactly as if you had pressed the keys. Try entering visual mode and then just typing `:echo mode()`. You will get the same result.

It looks like just running any ex command during visual mode exits visual mode at the beginning of execution. But if you enter visual mode again in the same ex command without moving the cursor first, it behaves like `gv` instead.

Couldn't find anything regarding that in docs though.

**Comment by amoffat** [comment]
Alright, I made some changes, and master is at 0.14.2.  Now that I have a more correct expectation of what `normal` does in visual mode, I think snake should be working how we both expect.  Give it a test and let me know what you think, and thanks for being patient and walking through the issue with me.

**Comment by Chronial** [comment]
Still doesn't work correctly – you can try it with the code sample I gave above. Now the selection is correct, but vim still does an error-beep.  I don't think you will be able to make this work that way – your wrapping is just way to invasive, there will be numerous corner-cases where this causes issues.

You simply do the wrapping only for functions that take an argument:
```
import inspect
args, varargs, keywords, defaults = inspect.getargspec(fn)
if args:
   do-wrapping()
```

**Comment by amoffat** [comment]
That's not a bad idea at all.  Could you elaborate on the error-beep?  My vim must not be configured to show those.

**Comment by Chronial** [comment]
It's a sound for me – details on the related configs is here: http://vim.wikia.com/wiki/Disable_beeping
Easiest way to test whether you have this set up: press `esc` while in normal mode – you should get a beep :).

**Comment by amoffat** [comment]
Aha, cool.  I don't know how it doesn't drive you crazy though :)

So I pushed up [your suggestion](https://github.com/amoffat/snake/commit/eab7af03e1feab7ad8a9d1f00d010a4e873c410b).  Now the visual code will generally only be called if the callback takes an argument.

I also dug around and found the source of the error bell as well, fixed by this https://github.com/amoffat/snake/commit/b68a415973f6d18fd5329389ff61ef061a49c00d.  Basically, I was hitting `\<esc>` first, regardless of what mode I was in, to reset back to normal mode, before restoring the old mode (like visual mode).  That code is part of the "preserve state" helpers that decorate functions throughout snake.  The idea is that if a function is decorated with `@preserve_state`, it should be able to do anything to registers, cursor, and mode, and when the function returns, all of those things are returned...an attempt to make helpers side-effect free in practice.  However, restoring the mode was always hitting `\<esc>` before setting the previous mode.

Now that I know about error bells, I'm a little annoyed there doesn't seem to be a way to detect them in the tests... https://github.com/amoffat/snake/commit/a7fcb1eaf964ed844d593f17515c08c276fef7e3

**Comment by amoffat** [comment]
Closing unless you notice another issue @Chronial.  Thanks again for the help

**Comment by Chronial** [comment]
Thx for resolving this :)
